language: objective-c
osx_image: xcode11.3
install:
  - bundle install
  - brew update
script:
  - bundle exec danger
  - xcodebuild -scheme Lumina -workspace Lumina.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.3'
  - xcodebuild -scheme Lumina -workspace Lumina.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=13.3'
