language: objective-c
osx_image: xcode9.1
env:
  - DANGER_GITHUB_API_TOKEN="27f9aaf101b7e26b3c6505bdde78ac9a9747c19f"
install:
  - bundle install
  - brew update
  - brew upgrade swiftlint
script:
  - bundle exec danger
  - xcodebuild -scheme Lumina -workspace Lumina.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 7 Plus,OS=10.3.1'
  - xcodebuild -scheme Lumina -workspace Lumina.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 7 Plus,OS=11.1'
