name: Pull Request Testing
on:
  pull_request:
jobs:
  build:
    runs-on: macos-10.15
    name: "Run Danger"
    steps:
        uses: actions/checkout@master
      - name: Danger
        uses: danger/swift@3.3.0
        with:
            args: --failOnErrors --no-publish-check
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_DANGER_API_TOKEN }}

      - name: "Run bundle exec"
        run: bundle exec danger

      - name: Run xcodebuild
        run: swift build -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios13.0-simulator"
