name: Pull Request Testing
on:
  pull_request:
jobs:
  build:
    runs-on: macos-10.15
    name: Check Build
    steps:
      - name: Import Actions
        uses: actions/checkout@master

      - name: Install Danger
        run: brew install danger/tap/danger-swift
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_DANGER_API_TOKEN }}

      - name: Run Danger
        run: danger-swift ci

      - name: Run xcodebuild
        run: swift build -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios13.0-simulator"
